### ISSUE TITLE
reduce turnaround time (especially "new" routers9

### ISSUE THREAD

**Issue by Adorfer** [dereulenspiegel/node-collector#20]
new routers need about 15-20 minutes to appear as MAC-adress (without data) in the nodegraph. 
And then it takes another 15-30 minutes until the node finally gets it. it floats just as a mac-adress on the map.

In plus, after an "autoupdater -f", the dynamic data takes about 5-10 minutes to appear (uptime).. but the sw-version (gluon release) takes nearly forever (30-45 minutes).

**Comment by ghost** [comment]
things:
- the node can be queried via neighbour-discovery with unicast and multicast and a valid response with hostname is returned
- console says: `ERRO[1518] Can't retrieve node infos to get the hostname  nodeid=xxxxxxxx`
- when the node is fully discovered the firstseen value is already at 15-20 minutes ago

**Comment by dereulenspiegel** [comment]
If you want to decrease the discovery time of new node, please read the documentation. There is a configuration value for this.
As for the `ERRO[1518] Can't retrieve node infos to get the hostname nodeid=xxxxxxxx`. This happens because you are using named nodes in the prometheus export. Node data can't be tagged with hostname when the hostname is not already discovered.
I can see no bugs here. Closing.

**Comment by ghost** [comment]
can you please reopen it or explain how to fix it?
The refresh times are set to 60 and 120 already.. The node is connected directly via cable / vpn. I don't see anything more. By the documentation do you mean the readme or is there more?
